#!/usr/bin/env php
<?php
/**
 * FuelPHP Oil Command Line Utility
 */
define('FUEL_START_TIME', microtime(true));
define('DOCROOT', __DIR__ . '/public');
define('APPPATH', __DIR__ . '/fuel/app/');
define('COREPATH', __DIR__ . '/fuel/core/');

require COREPATH.'classes/oil/oil.php';
